/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.evertones;

import org.evertones.selenium.WebDriverFactory;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import java.net.MalformedURLException;

public class App {

    private static final Boolean isRemote = true;
    private static final Boolean isChrome = false;

    public static void main(String[] args) throws MalformedURLException {

        WebDriver webDriver = null;
        if (isChrome) {
            webDriver = new App().getChromeInstance();
        }
        else {
            webDriver = new App().getFirefoxInstance();
        }

        webDriver.get("https://www.google.com");

        WebElement input = webDriver.findElement(By.cssSelector("input[name='q']"));

        input.sendKeys("test");
        input.sendKeys(Keys.ENTER);

        WebElement testResultsStat = webDriver.findElement(By.id("result-stats"));

        System.out.println("Result: " + testResultsStat.toString());

        webDriver.quit();
    }

    private WebDriver getFirefoxInstance() throws MalformedURLException {
        WebDriverFactory wdf = new WebDriverFactory();
        WebDriver webDriver = null;
        if (isRemote) {
            webDriver = wdf.createRemoteFirefoxInstance();
        }
        else {
            webDriver = wdf.createFirefoxInstance();
        }
        return webDriver;
    }

    private WebDriver getChromeInstance() throws MalformedURLException {
        WebDriverFactory wdf = new WebDriverFactory();
        WebDriver webDriver = null;
        if (isRemote) {
            webDriver = wdf.createRemoteChromeInstance();
        }
        else {
            webDriver = wdf.createChromeInstance();
        }
        return webDriver;
    }


}
